projects:
  zenhub:
    schema: src/main/graphql/zenhub/schema.json
    include: src/main/graphql/zenhub/**/*.graphql
  github:
    schema: src/main/graphql/github/schema.json
    include: src/main/graphql/github/**/*.graphql